# Generated by Django 3.0.7 on 2020-06-22 23:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=60)),
                ('Course', models.IntegerField(blank=True, default='', max_length=20)),
                ('Instructor', models.CharField(blank=True, default='', max_length=60)),
                ('Duration', models.FloatField(blank=True, default='', max_length=40)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
