# Generated by Django 3.0.7 on 2020-06-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
